# Generated by Django 2.0.4 on 2018-05-02 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0002_pk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pk',
            old_name='id',
            new_name='dk_id',
        ),
    ]
